function uimg = undistort_bc(img, K, k)
    cameraParams = cameraParameters(...
                    'IntrinsicMatrix', K',...
                    'RadialDistortion', k(1:2),...
                    'TangentialDistortion', k(3:4));
    uimg = undistortImage(img, cameraParams,...
                        'FillValues', [255; 255; 255],...
                        'OutputView', 'full');
end